### ISSUE TITLE
Feature: Make this readme match hot.opensauced.pizza

### ISSUE THREAD

**Issue by bdougie** [open-sauced/contributor.info#5]
### Type of feature

📝 Documentation

### Current behavior

Currently the ream the standard next one. 

### Suggested solution

update the readme to look and feel similar to https://github.com/open-sauced/hot/blob/beta/README.md

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
I'll `.take` this one since I doubt there's anyone else ready, since this is a nextjs app, we could add cloud IDEs and our VSC global config (the one we made in gitpod last year) so that people can actually start a dev session from the README, what do you think?
